#L3 OSPF with VRRP
---

- name: Configure L3 OSPF with VRRP
  hosts: switch[0]


  vars:
    - trunk_csv_file: l3_bgp_with_vrrp_trunk.csv
    - vlan_csv_file: l3_bgp_with_vrrp_vlan.csv
    - vlag_csv_file: l3_bgp_with_vrrp_vlag.csv
    - vrrp_csv_file: l3_bgp_with_vrrp_vrrp.csv
    - ospf_csv_file: l3_ospf_with_vrrp_ospf.csv

  tasks:
    - name: Create cluster
      pn_cluster_creation:
        pn_switch_list: "{{ groups['switch'] }}"

    - name: Create vlans
      pn_vlan_creation:
        pn_switch: "{{ inventory_hostname }}"
        pn_vlan_data: "{{ lookup('file', '{{ vlan_csv_file }}') }}"

    - name: Create trunks
      pn_trunk_creation:
        pn_switch_list: "{{ groups['switch'] }}"
        pn_trunk_data: "{{ lookup('file', '{{ trunk_csv_file }}') }}"

    - name: Create vlags
      pn_vlag_creation:
        pn_switch_list: "{{ groups['switch'] }}"
        pn_vlag_data: "{{ lookup('file', '{{ vlag_csv_file }}') }}"

    - name: Create vrouter
      pn_vrouter_creation:
        pn_loopback_ip: "20.10.10.1"
        pn_vrrp_id: "18"
        pn_switch_list: "{{ groups['switch'] }}"

    - name: Configure VRRP
      pn_vrrp_creation:
        pn_switch_list: "{{ groups['switch'] }}"        
        pn_vrrp_id: "18"
        pn_vrrp_data: "{{ lookup('file', '{{ vrrp_csv_file }}') }}"

    - name: Configure OSPF
      pn_ospf_configuration:
        pn_switch_list: "{{ groups['switch'] }}"
        pn_ospf_data: "{{ lookup('file', '{{ ospf_csv_file }}') }}"

